## 任务
抓取*10*条的*今日*新闻

## 注意事项：
不要包含citation

## 输出：
1. 请按照种类，标题，摘要和链接，生成一份**csv**文件。
2. 以markdown格式

In [12]:
import pandas as pd



df = pd.read_csv('news-20260501.csv', encoding='utf-8')

df_styled = df.style.set_properties(subset=df.columns, **{'text-align': 'left'})
df_styled.set_table_styles([dict(selector='th', props=[('text-align', 'left')])])

df_styled

In [ ]:
movie_id="34780991"
url = f"https://movie.douban.com/subject/34780991/comments?satus=P"

import requests
from bs4 import BeautifulSoup
import pandas as pd

raw_text:str=""

## manual open url in browser

with open('douban-34780991.txt', 'r', encoding='utf-8') as f:
    raw_text = f.read()

In [32]:
soup = BeautifulSoup(raw_text, 'html.parser')
# soup

comments_data = []
comments = soup.find_all('div', class_='comment-item')


for comment in comments:
    commenter = comment.find('span', class_='comment-info').find('a').text.strip()
    rating = comment.find('span', class_='rating')['class'][0] if comment.find('span', class_='rating') else 'No rating'
    content = comment.find('span', class_='short').text.strip()

    comments_data.append([commenter,rating, content])

In [ ]:
df = pd.DataFrame(comments_data, columns=["评论人", "评分", "内容"])
df

,评论人,评分,内容
0,南赫,allstar20,母亲为爱牺牲，仙鹤也要护老登；裙子软绵可撕，石矶也要服美役。
1,海底,allstar50,申公豹：小镇做题家的一生
2,Fang,allstar30,烦透了这种高层隐身、中层搞事、底层遭殃的设定，无数次看得我血压飙升，哪吒虽然设定是魔，行事倒...
3,朝暮雪,allstar30,很多桥段很低俗，第一部就有这样的问题，但就是不改，因为导演觉得拍得再低俗都有大把的人去看，不...
4,丁小雨,allstar40,感觉“我命由我不由天”的是申公豹，申公豹真的好努力，努力的小镇做题家，努力攀附强者才能让自己...
5,居无间,allstar50,饺子的水准真的稳。本片是对第一部的全面升级，阴阳美学更加极致，水与火、红与蓝、善与恶等等元素...
6,茗政,allstar40,虽没有第一部“我命由我不由天”的惊艳金句，但更多了些“怎能不知道这世间的规则，由谁所定？”的...
7,boboan,allstar50,何为“反父权”？79年的哪吒直观地以“反父亲的教导”来代表反父权的思想，19年的魔童哪吒横空...
8,ChristopherCC,allstar40,能不能别放3D版本。
9,团小纸,allstar50,中国人有共同集体记忆的神话传说一定会提到哪吒闹海，所以春节看哪吒也是属于中国人自己的仪式感！...
10,凌林,allstar50,申公豹视角get:有自己的脑子是一件多么值得庆幸的事
11,小烨,allstar50,中国传统神话故事需要在创新中传承，哪吒系列就是一个好案例。哪吒本来就是我很喜欢的一个神话人物...
12,kako,allstar50,太帅了啊啊啊啊啊啊啊啊啊！！！！！东海龙王太帅了！！！！！！
13,天命咸鱼111,allstar50,家人们谁懂啊，敖丙也太适合当老婆了
14,[未注销],allstar40,《哪吒第二部：战火陈塘》。\n讲出来了；看进去了。
15,白影,allstar50,活该赚钱的水平
16,ハル,allstar40,这才是真正的封神榜吧。政治明喻的内核剑指东方厚黑智慧。作为正统权力的“阐教”如何通过资源分配...
17,安托万的黑眼睛,allstar50,特效太牛了，太燃了，依然很搞笑，我们的吒儿瞬间长大，破茧成蝶，涅槃重生。
18,蝴蝶不梦庄周,allstar40,贴合时代背景，幽默的片段的确能够吸引娱乐时代大众审美；总的来说：不管从特效，人物设定，造型设...
19,咚噢,allstar40,承认很厉害，但说实话希望女性角色不再是推动剧情的NPC

In [35]:
raw_review:str=""

## manual open url in browser

with open('douban-34780991-review.txt', 'r', encoding='utf-8') as f:
    raw_review = f.read()

In [75]:

soup = BeautifulSoup(raw_review, 'html.parser')
# soup

reviews_data = []
reviews = soup.find_all('div', class_='review-item')

for review in reviews:
    # print(review)
    
    reviewer = review.select_one('header a.name').text.strip()
    rating = review.select_one('span.main-title-rating')['title']
    date = review.select_one('span.main-meta').text.strip()

    header = review.select_one('div.main-bd h2')
    title = header.text.strip()
    url = header.select_one('a')['href']
    short_content = review.select_one('div.short-content').text.strip()

    action = review.select_one('div.action')
    up = action.select_one('a.up').text.strip()
    down = action.select_one('a.down').text.strip()

    reviews_data.append([reviewer, rating, date, title,  short_content,  up, down, url])

In [76]:
df = pd.DataFrame(reviews_data, columns=["评论人", "评分", "日期", "标题", "短评", "赞", "踩", "链接"])
df

,评论人,评分,日期,标题,短评,赞,踩,链接
0,云霁,较差,2025-01-30 04:07:28,这烂成一团的剧情到底谁在夸,凌晨三点没精力整理思路了，乱七八糟想到哪儿写到哪儿 有剧透慎点 · 特效画面非常好，完全值回...,5446,1840,https://movie.douban.com/review/16459075/
1,葛大爷,较差,2025-01-29 21:44:46,把仙翁塑造成世俗意义上的恶人，这个电影立意就落入俗套了,这篇影评可能有剧透\n\n 欢迎讨论，骂人的都...,4055,1357,https://movie.douban.com/review/16457209/
2,飛,较差,2025-01-30 20:45:21,唯余叹息——哪吒2的成功是快餐流量的狂欢，也是对电影艺术的侮辱,这篇影评可能有剧透\n\n 哪吒2开分8.5，...,3634,1064,https://movie.douban.com/review/16462035/
3,猪Q,较差,2025-01-29 15:23:06,看过一天后，从三星降到两星，喜欢这部电影的这么多，不差我陈塘关百姓一个,这篇影评可能有剧透\n\n 这根本就是一部不该...,3965,2000,https://movie.douban.com/review/16454579/
4,搬砖侠,力荐,2025-01-29 18:39:38,哪吒反叛的力量：从弑父到弑神,当银幕上哪吒在天元鼎内完成涅槃浴火重生时，相信所有人都会赞同，这绝不是一部普通的续作。时隔六...,2100,317,https://movie.douban.com/review/16455860/
5,北桥,很差,2025-01-30 01:14:07,最没素质的片子，内核和技法没一个能看,牢记一点：销量和质量没有必然关系，否则中国最好的文学作品是《斗破苍穹》。 二次编辑（2.9）...,1896,661,https://movie.douban.com/review/16458713/
6,导师永远的战士,还行,2025-01-29 16:16:01,合格的商业片，但仍想提出质疑,作为贺岁档电影，哪吒无疑是一部合格的商业片。故事节奏快，至少看着不会无聊，围绕亲情线展开，也...,1303,318,https://movie.douban.com/review/16454926/
7,恰帕斯东风电囼,较差,2025-02-11 20:12:05,《哪吒2》与被它击中的时代保守情绪,在院线春节档正式开启以前，几乎很少有人预料到一部动漫能领跑整个档期，并创下多个票房记录。除去...,800,229,https://movie.douban.com/review/16497950/
8,nothing纳森,推荐,2025-01-29 20:56:52,若天下无路，我就开出一条路,作为第一批走进电影院的观众，趁着热乎劲儿，如实叨叨，等待了五年之久的《哪吒2》，整出了啥绝活...,972,140,https://movie.douban.com/review/16456867/
9,owl,力荐,2025-01-29 13:01:05,致你我之辈 致父母之辈,这篇影评可能有剧透\n\n 看完走出电影院 问...,858,140,https://movie.douban.com/review/16453696/
10,垃圾别撒野！,很差,2025-01-29 19:20:23,再好的故事，也会变成一盘凉透的饺子【涉剧透】,这篇影评可能有剧透\n\n 【看到各位的评论真...,1336,605,https://movie.douban.com/review/16456147/
11,徐旷来,力荐,2025-01-26 08:42:49,哪吒最早出自哪？《哪吒之魔童闹海》,哪吒，一听这名字的读音，就不像汉语。 哪吒从何而来？从印度来。古人翻译佛经，有在汉字左边加口...,611,93,https://movie.douban.com/review/16448294/
12,远方阿怪,还行,2025-02-16 13:20:58,《哪吒2》让人不适的根本——聊聊中式动画“燃”的困局,这篇影评可能有剧透\n\n 原载于公号“远方阿...,336,23,https://movie.douban.com/review/16507165/
13,circularuins,较差,2025-02-12 12:02:41,向我的朋友解释为什么我不喜欢哪吒,这篇影评可能有剧透\n\n 记录一下我和她的聊...,562,66,https://movie.douban.com/review/16499182/
14,啾啾喳喳,较差,2025-01-30 14:09:47,哪吒是斗牛场的一块红色披风，理性交流被严令禁止。,这篇影评可能有剧透\n\n 一味炫技完全没有内...,642,173,https://movie.douban.com/review/16460507/
15,蓝想容,较差,2025-01-30 00:32:38,反正给我看恶心了,这篇影评可能有剧透\n\n 看完后悔了，提前订...,434,151,https://movie.douban.com/review/16458485/
16,Meanda,较差,2025-01-31 21:40:53,虚假的反父权叙事,这篇影评可能有剧透\n\n 非常好的美术和特效...,303,77,https://movie.douban.com/review/16466146/
17,人间烟火,力荐,2025-01-29 11:57:56,我勒个黑神话哪吒啊,这篇影评可能有剧透\n\n 怎么能好看到这个地...,313,87,https://movie.douban.com/review/16453268/
18,匡轶歌,力荐,2025-01-30 14:27:43,哪吒的考编之路，可怕,_________ 强得可怕。 不说什么“一枝独秀”“最大赢家”，仿佛电影界的生态只能是无法...,234,46,https://movie.douban.com/review/16460574/